export const actionTypes = {
    ADD_TEAM:"ADD_TEAM",
    REMOVE_TEAM:"REMOVE_TEAM",
    ADD_PLAYER:"ADD_PLAYER",
    REMOVE_PLAYER:"REMOVE_PLAYER",
    ADD_PLAYER_TO_TEAM:"ADD_PLAYER_TO_TEAM",
    REMOVE_PLAYER_FROM_TEAM:"REMOVE_PLAYER_FROM_TEAM",
}